# Generated by Django 3.0.3 on 2021-01-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='acctype',
            field=models.CharField(default='Public', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='foll_req',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
