# Generated by Django 3.0.3 on 2021-01-09 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210109_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 23, 24, 50, 507468)),
        ),
        migrations.AlterField(
            model_name='post',
            name='userid',
            field=models.CharField(default='', max_length=25),
        ),
    ]
