# Generated by Django 3.0.3 on 2021-03-31 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210111_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_picture',
            field=models.ImageField(blank=True, default='display_pictues/default_nice.jpg', upload_to='display_pictures/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 20, 7, 2, 403123)),
        ),
        migrations.AlterField(
            model_name='post',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
    ]
