# Generated by Django 3.0.3 on 2021-01-09 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 23, 3, 5, 837970)),
        ),
    ]
