# Generated by Django 3.0.3 on 2021-01-11 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210109_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likediff',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 20, 4, 15, 334529)),
        ),
    ]
