# Generated by Django 3.0.3 on 2021-01-11 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210111_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 21, 9, 50, 509935)),
        ),
        migrations.AlterField(
            model_name='post',
            name='likediff',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
