# Generated by Django 3.0.3 on 2021-03-31 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210331_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 20, 7, 26, 328412)),
        ),
    ]
